FROM openjdk:18-jdk-alpine

ARG KAFKA_SERVER localhost:9092
ENV KAFKA_SERVER ${KAFKA_SERVER}

# API arguments
ARG AGENT_LOAD_URL http://127.0.0.1:8888/api/v1/agents
ENV AGENT_LOAD_URL ${AGENT_LOAD_URL}

# Database arguments
ARG JDBC_DATABASE_PG_URL jdbc:postgresql://127.0.0.1:5432/telemetry
ENV JDBC_DATABASE_PG_URL ${JDBC_DATABASE_PG_URL}

ARG R2DBC_DATABASE_PG_URL r2dbc:postgresql://127.0.0.1:5432/telemetry
ENV R2DBC_DATABASE_PG_URL ${R2DBC_DATABASE_PG_URL}

ARG JDBC_DATABASE_PG_USER postgres
ENV JDBC_DATABASE_PG_USER ${JDBC_DATABASE_PG_USER}

ARG JDBC_DATABASE_PG_PASSWORD postgres
ENV JDBC_DATABASE_PG_PASSWORD ${JDBC_DATABASE_PG_PASSWORD}

ARG JAR_FILE=target/message-subscriber.jar

ADD ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar"]